#!/bin/bash

# copyleft 2015 teodorescu.serban@gmail.com

mypath="hdx-install"

if [ -z $EDITOR ]; then
  EDITOR=mcedit
fi

if [ ! -d hdx-install-private ]; then
  git clone https://hdx-user@bitbucket.org/teodorescuserban/hdx-install-private.git
fi

if [ $? -eq 0 ]; then
    echo "Done."

    echo "Please customize the public vars."
    echo "The prefix, http and https ports maybe?"
    echo "Starting $EDITOR for you in 20 seconds."
    echo "Why so long? So you can read above!"
    sleep 20
    $EDITOR $mypath/set_vars

    echo "Creating docker-compose configuration file..."
    source $mypath/set_vars
    source hdx-install-private/set_private_vars
    envsubst < $mypath/docker-compose.tpl > docker-compose.yml

    echo "Done. Inspect it."
    echo "Starting $EDITOR for you in 20 seconds."
    echo "Why so long? So you can read above!"
    sleep 20
    $EDITOR docker-compose.yml

    # echo "You are ready to start the HDX environment!"
else
    echo "Private repo cloning failed! Start again!"
fi
