#!/bin/bash

# copyleft 2015 teodorescu.serban@gmail.com

mypath="hdx-install"

if [ -z $EDITOR ]; then
  which mcedit > /dev/null
  if [ $? -eq 0 ]; then
    EDITOR=mcedit
  else
    which nano > /dev/null
    if [ $? -eq 0 ]; then
      EDITOR=mcedit
    else
      EDITOR=vi
    fi
  fi
fi

if [ ! -d hdx-install-private ]; then
  git clone https://hdx-user@bitbucket.org/teodorescuserban/hdx-install-private.git
fi

if [ $? -eq 0 ]; then
    echo "Done."

    echo "Please customize the public vars."
    echo "The prefix, http and https ports maybe?"
    read -p "Press any key to start $EDITOR. " -n 1 -r
    $EDITOR $mypath/set_vars

    echo "Creating docker-compose configuration file..."
    source $mypath/set_vars
    source hdx-install-private/set_private_vars
    envsubst < $mypath/common.tpl > common.yml

    echo "Done. Inspect it."
    read -p "Press any key to start $EDITOR. " -n 1 -r
    $EDITOR common.yml

    # echo "You are ready to start the HDX environment!"
else
    echo "Private repo cloning failed! Start again!"
fi
