# ckan db_private
HDX_CKANDB_DB_DATASTORE=${HDX_CKANDB_DB_DATASTORE}
HDX_CKANDB_DB=${HDX_CKANDB_DB}
HDX_CKANDB_PASS_DATASTORE=${HDX_CKANDB_PASS_DATASTORE}
HDX_CKANDB_PASS=${HDX_CKANDB_PASS}
HDX_CKANDB_USER_DATASTORE=${HDX_CKANDB_USER_DATASTORE}
HDX_CKANDB_USER=${HDX_CKANDB_USER}
